### ISSUE TITLE
Backward Compatibility

### ISSUE THREAD

**Issue by rifaideen** [cniska/yii-auth#101]
Auth module does compatible with your bootstrap extension available on http://www.yiiframework.com/extension/bootstrap but you said that it was compatible with that.

**Comment by cniska** [comment]
The latest version of Auth is using a rewrite of my bootstrap extension called Yiistrap, which is available at http://getyiistrap.com.

**Comment by rifaideen** [comment]
but I was fully utilising your previous version of extension in my project and now to implement auth module it does not compatible with that. so now I am rewriting the entire things for auth module due to version incompatiblity

**Comment by cniska** [comment]
I understand your problem, but as the project has moved on (in order to improve the quality of the project) to use Yiistrap you have two choices, either stay with your current version of Auth or upgrade to the latest stable version of Auth and use it together with Yiistrap.

As a sidenote I want to say that Yiistrap has a lot more potential than yii-bootstrap ever had. The biggest problem with yii-bootstrap was that it was just a collection of widgets more or less. Yiistrap has an awesome HTML helper (that extends Yii's CHtml) which all the widgets use to render their HTML.

**Comment by rifaideen** [comment]
ok. now I adjusted my layouts and forms according to new format
